import { jsPDF } from "jspdf";
import { getLanguage } from "@/lib/leaseOptions";

function wrap(doc, text, x, y, w, lh, style) {
  doc.setFont("helvetica", style || "normal");
  const lines = doc.splitTextToSize(text || "", w);
  lines.forEach((ln) => {
    if (y > 280) {
      doc.addPage();
      y = 18;
    }
    doc.text(ln, x, y);
    y += lh;
  });
  return y;
}

export function generateReportPdf(record) {
  const doc = new jsPDF();
  const lang = getLanguage(record.language);
  const score = Number(record.overall_risk_score) || 0;
  let y = 18;

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20);
  doc.text("LeaseLens — Analysis Report", 14, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90);
  doc.text(record.title || "Untitled lease", 14, y);
  y += 6;
  doc.text(
    `Jurisdiction: ${record.jurisdiction || "-"}    Lease type: ${record.lease_type || "-"}    Language: ${lang.label}`,
    14,
    y
  );
  y += 6;
  doc.text(`Overall risk score: ${score}/100`, 14, y);
  y += 6;
  doc.text(`Generated: ${new Date(record.created_date).toLocaleString()}`, 14, y);
  y += 6;

  doc.setDrawColor(220);
  doc.line(14, y, 196, y);
  y += 8;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20);
  doc.text("Summary", 14, y);
  y += 6;
  y = wrap(doc, record.summary || "", 14, y, 180, 5);
  y += 4;

  const clauses = record.clauses || [];
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Flagged clauses (${clauses.length})`, 14, y);
  y += 6;

  clauses.forEach((c, i) => {
    if (y > 270) {
      doc.addPage();
      y = 18;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(20);
    doc.text(`${i + 1}. ${c.category || "Clause"}  [${(c.risk_level || "").toUpperCase()}]`, 14, y);
    y += 5;
    doc.setFontSize(10);
    y = wrap(doc, `Clause: ${c.clause_text || ""}`, 14, y, 180, 5, "italic");
    y = wrap(doc, `Plain language: ${c.plain_language || ""}`, 14, y, 180, 5);
    y = wrap(doc, `Why it matters: ${c.why_it_matters || ""}`, 14, y, 180, 5);
    y = wrap(doc, `Relevant law: ${c.legal_mapping || ""}`, 14, y, 180, 5);
    y = wrap(doc, `Recommendation: ${c.recommendation || ""}`, 14, y, 180, 5);
    y += 4;
  });

  y = Math.max(y, 250);
  if (y > 280) {
    doc.addPage();
    y = 18;
  }
  doc.setDrawColor(220);
  doc.line(14, y, 196, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(140);
  wrap(
    doc,
    "This report is generated by AI and is for general information only. It is not legal advice. For binding guidance, consult a qualified tenant-rights attorney.",
    14,
    y,
    180,
    4
  );

  const safeName = (record.title || "report").replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`leaselens-${safeName}.pdf`);
}